FROM golang:1.20-alpine as build
RUN apk --no-cache add curl busybox-extras
RUN go install github.com/mitranim/gow@latest

WORKDIR /code
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

FROM build

WORKDIR /code
COPY ./go.mod ./
COPY ./go.sum ./

COPY ./libs ./libs
COPY ./apps/dispatcher ./apps/dispatcher
RUN go mod tidy

CMD ["gow", "run", "./apps/dispatcher"]